#version: '3.8'
#
#services:
#  app1:
#    build: .
#    environment:
#      - PORT=8081
#    networks:
#      - app-network
#
#  app2:
#    build: .
#    environment:
#      - PORT=8082
#    networks:
#      - app-network
#
#  app3:
#    build: .
#    environment:
#      - PORT=8083
#    networks:
#      - app-network
#
#  app:
#    build: .
#    environment:
#      - PORT=8080
#    networks:
#      - app-network
#
#  nginx:
#    image: nginx:alpine
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#    depends_on:
#      - app
#    networks:
#      - app-network
#
#networks:
#  app-network:
#    driver: bridge